- name: Create a directory if it does not exist
  file:
    path: /usr/local/mingdao
    state: directory
    
- name: Create a file as the identity file
  shell: touch /usr/local/mingdao/first
    
- name: Pull mingdao docker image
  shell: |
    docker pull mdpublic/mingdaoyun-community:"{{mingdao_docker_community_version}}"
    docker pull mdpublic/mingdaoyun-doc:"{{mingdao_docker_doc_version}}"
  
- name: Download mingdao installation tool from {{mingdao_download_url}}
  shell: |
    curl {{mingdao_download_url}} | tar xvz -C /usr/local/mingdao
    bash /usr/local/mingdao/service.sh start
  args:
    chdir: /tmp

- name: add startup scripts sys.sh to Server
  template:
    src: sys.sh
    dest: /usr/local/mingdao

- name: add sys.sh to /etc/rc.local
  shell: |
    echo '#!/bin/bash' > /etc/rc.local
    echo '/bin/bash /usr/local/mingdao/sys.sh > /usr/local/mingdao/service.log 2>&1' >> /etc/rc.local
    chmod 755 /etc/rc.local
